---
- name: simplephp
  hosts: node
  gather_facts: yes
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: config httpd to php
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root

    - name: grep php
      shell: "sudo amazon-linux-extras |grep php"

    - name: install php all
      shell: "sudo yum -y install php-cli php-common php-gd php-mbstring php-mysqlnd php-pdo php-fpm php-xml php-opcache php-zip php-bcmath"

    - name: install php-mysql
      yum:
        name: php-pdo
        state: present

    - name: install git
      yum:
        name: git
        state: present

    - name: remove file
      shell: "rm -rf simplephp"
      args:
        warn: no

    - name: get html
      shell: "git clone https://github.com/kpsz0528/simplephp.git"

    - name: mv index
      shell: "mv -f ./simplephp/index.php /var/www/html/"

    - name: mv php
      shell: "mv -f ./simplephp/signup_action.php /var/www/html/"

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
